
# tap repositories and their packages

tap homebrew/core
brew ack
brew ant
brew aom
brew apr
brew apr-util
brew asciidoc
brew autoconf
brew awscli
brew bdw-gc
brew berkeley-db
brew boost
brew brew-cask-completion
brew brotli
brew bzip2
brew c-ares
brew cabal-install
brew cairo
brew ccache
brew cmake
brew cocot
brew composer
brew coreutils
brew cowsay
brew cscope
brew ctags
brew czmq
brew dav1d
brew direnv
brew docbook
brew docbook-xsl
brew docker
brew docker-compose
brew docker-machine
brew doxygen
brew ffmpeg
brew figlet
brew flac
brew fontconfig
brew fontforge
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gawk
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghc
brew ghi
brew ghostscript
brew giflib
brew gifsicle
brew git
brew glib
brew gmp
brew gnu-getopt
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew graphviz
brew grep
brew gts
brew guile
brew harfbuzz
brew hub
brew hugo
brew icu4c
brew ilmbase
brew imagemagick
brew jasper
brew jbig2dec
brew jemalloc
brew jenkins
brew jpeg
brew jq
brew lame
brew leptonica
brew libass
brew libbluray
brew libde265
brew libev
brew libevent
brew libffi
brew libheif
brew libidn2
brew liblqr
brew libogg
brew libomp
brew libpng
brew libpthread-stubs
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libspiro
brew libtasn1
brew libtiff
brew libtool
brew libuninameslist
brew libunistring
brew libuv
brew libvidstab
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew luajit
brew lz4
brew lzo
brew m4
brew mas
brew mcrypt
brew mecab
brew mecab-ipadic
brew memcached
brew mercurial
brew mhash
brew mpdecimal
brew mpfr
brew ncurses
brew netpbm
brew nettle
brew nghttp2
brew nkf
brew node
brew nodebrew
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjdk@11
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew peco
brew perl
brew pixman
brew pkg-config
brew python@3.9
brew rav1e
brew rbenv
brew rbenv-gemset
brew re2c
brew readline
brew reattach-to-user-namespace
brew redis
brew rrdtool
brew rubberband
brew ruby
brew ruby-build
brew scons
brew sdl2
brew shared-mime-info
brew shellcheck
brew snappy
brew source-highlight
brew speex
brew sqlite
brew srt
brew ssh-copy-id
brew terminal-notifier
brew tesseract
brew the_silver_searcher
brew theora
brew tig
brew tmux
brew tree
brew unbound
brew unixodbc
brew utf8proc
brew v8
brew vim
brew webp
brew wget
brew x264
brew x265
brew xmlto
brew xorgproto
brew xvid
brew xz
brew zeromq
brew zimg
brew zlib
brew zsh
brew zsh-completions
brew zsh-syntax-highlighting
brew zstd

tap homebrew/bundle

tap homebrew/cask-versions

tap homebrew/cask
cask adobe-air
cask airdroid
cask alfred
cask android-ndk
cask android-sdk
cask appcleaner
cask atom
cask bartender
cask bettertouchtool
cask box-sync
cask burn
cask caffeine
cask cheatsheet
cask coccinellida
cask diffmerge
cask docker
cask docker-toolbox
cask dropbox
cask eclipse-java
cask eclipse-php
cask evernote
cask firefox
cask fluid
cask genymotion
cask gimp
cask google-chrome
cask google-japanese-ime
cask growlnotify
cask gyazo
cask ifunbox
cask inkscape
cask ios-console
cask istat-menus
cask iterm2
cask licecap
cask messenger
cask mplayerx
cask mysqlworkbench
cask onyx
cask postico
cask remote-desktop-manager
cask scapple
cask sequel-pro
cask shuttle
cask skitch
cask skype
cask slack
cask slate
cask sourcetree
cask sublime-text
cask svnx
cask texturepacker
cask the-unarchiver
cask timemachineeditor
cask vagrant
cask virtualbox
cask visual-studio-code
cask wireshark
cask x-mirage
cask xquartz

tap argon/mas

tap rcmdnk/file
brew brew-file

tap sanemat/font
brew ricty --with-powerline

# App Store applications
appstore 443987910 1Password (6.8.9)
appstore 726828968 Astro (1.137)
appstore 460883588 ATOK Pad (2.0.7)
appstore 415181149 Calendars (3.0)
appstore 478570084 CompareMerge (2.18)
appstore 411643860 DaisyDisk (4.12.1)
appstore 642220194 DeskConnect (1.2.2)
appstore 408981434 iMovie (10.2.3)
appstore 409183694 Keynote (11.0.1)
appstore 539883307 LINE (6.7.2)
appstore 409203825 Numbers (11.0)
appstore 409201541 Pages (11.0)
appstore 1176895641 Spark (2.9.22)
